In [1]:
import pandas as pd
import xlrd

In [14]:
path = r"H:\Python\Atividade06\Tabela5-sem_emprego_2012.csv"
path2 = r"H:\Python\Atividade06\Tabela5-sem_emprego_2026.csv"
path3 = r"H:\Python\Atividade06\Tabela 1.1.1.xls"

In [34]:
t2012 = pd.read_csv(path, sep=";", encoding="utf-8-sig")
t2026 = pd.read_csv(path2, sep=";", encoding="utf-8-sig")

In [4]:
t2012

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1)
0,AC,12,Acre,"45,3","54,7"
1,AL,27,Alagoas,"44,7","55,3"
2,AM,13,Amazonas,"47,5","52,5"
3,AP,16,Amapá,"48,1","51,9"
4,BA,29,Bahia,"43,8","56,2"
5,CE,23,Ceará,"51,1","48,9"
6,DF,53,Distrito Federal,41,59
7,ES,32,Espírito Santo,"46,4","53,6"
8,GO,52,Goiás,41,59
9,MA,21,Maranhão,"47,2","52,8"
10,MG,31,Minas Gerais,"43,1","56,9"
11,MS,50,Mato Grosso do Sul,"47,2","52,8"
12,MT,51,Mato Grosso,"44,1","55,9"
13,PA,15,Pará,"43,2","56,8"
14,PB,25,Paraíba,"44,4","55,6"
15,PE,26,Pernambuco,"43,9","56,1"
16,PI,22,Piauí,"51,2","48,8"
17,PR,41,Paraná,"40,3","59,7"
18,RJ,33,Rio de Janeiro,"44,2","55,8"
19,RN,24,Rio Grande do Norte,51,49
20,RO,11,Rondônia,"43,4","56,6"
21,RR,14,Roraima,"41,8","58,2"
22,RS,43,Rio Grande do Sul,"42,8","57,2"
23,SC,42,Santa Catarina,"42,7","57,3"
24,SE,28,Sergipe,"46,5","53,5"
25,SP,35,São Paulo,"45,4","54,6"
26,TO,17,Tocantins,"55,3","44,7"

In [29]:
comp = t2012.merge(t2026, on=["Sigla", "Código", "Estado"], how="inner")

In [30]:
comp

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1),Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1)
0,AC,12,Acre,"45,3","54,7","53,2","46,8"
1,AL,27,Alagoas,"44,7","55,3","50,7","49,3"
2,AM,13,Amazonas,"47,5","52,5","46,8","53,2"
3,AP,16,Amapá,"48,1","51,9","51,1","48,9"
4,BA,29,Bahia,"43,8","56,2","44,7","55,3"
5,CE,23,Ceará,"51,1","48,9","52,7","47,3"
6,DF,53,Distrito Federal,41,59,"47,9","52,1"
7,ES,32,Espírito Santo,"46,4","53,6","47,5","52,5"
8,GO,52,Goiás,41,59,"47,5","52,5"
9,MA,21,Maranhão,"47,2","52,8","49,1","50,9"
10,MG,31,Minas Gerais,"43,1","56,9","48,6","51,4"
11,MS,50,Mato Grosso do Sul,"47,2","52,8","45,3","54,7"
12,MT,51,Mato Grosso,"44,1","55,9","42,8","57,2"
13,PA,15,Pará,"43,2","56,8","48,3","51,7"
14,PB,25,Paraíba,"44,4","55,6","48,9","51,1"
15,PE,26,Pernambuco,"43,9","56,1","48,7","51,3"
16,PI,22,Piauí,"51,2","48,8","55,1","44,9"
17,PR,41,Paraná,"40,3","59,7","46,3","53,7"
18,RJ,33,Rio de Janeiro,"44,2","55,8","45,4","54,6"
19,RN,24,Rio Grande do Norte,51,49,"48,2","51,8"
20,RO,11,Rondônia,"43,4","56,6",33,67
21,RR,14,Roraima,"41,8","58,2","43,4","56,6"
22,RS,43,Rio Grande do Sul,"42,8","57,2","47,4","52,6"
23,SC,42,Santa Catarina,"42,7","57,3","44,6","55,4"
24,SE,28,Sergipe,"46,5","53,5","40,3","59,7"
25,SP,35,São Paulo,"45,4","54,6","46,2","53,8"
26,TO,17,Tocantins,"55,3","44,7","46,2","53,8"

In [41]:
tIBGE = pd.read_excel(path3, engine="xlrd", header=5)
tIBGE

,Unnamed: 0,Total,Por sexo e cor ou raça,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,Total,NaN,Homem,NaN,Mulher,NaN
1,NaN,NaN,Branca,Preta ou parda,Branca,Preta ou parda,Branca,Preta ou parda
2,Brasil,16.985781,16.54593,17.333142,11.705136,11.74633,20.404106,22.037998
3,Norte,16.187037,15.925246,16.256032,11.588653,11.514646,19.29578,20.534188
4,Rondônia,17.014162,16.727733,17.101523,12.111127,12.54408,20.412887,21.06141
5,Acre,13.606903,13.806929,13.541399,10.79612,9.686983,16.130352,16.710754
6,Amazonas,16.807290,15.987545,16.995493,12.233043,12.822584,18.764969,20.716986
7,Roraima,13.639257,13.651755,13.633606,10.814803,10.476601,16.135877,16.560244
8,Pará,16.474268,16.181627,16.560239,11.524306,11.026707,19.83511,21.591144
9,Amapá,13.586656,14.38918,13.415091,11.116821,10.749444,16.648579,15.908487
10,Tocantins,15.815781,15.701788,15.768728,10.733863,11.682616,19.663713,19.629399
11,Nordeste,18.499396,18.1517,18.610911,11.723907,11.848436,22.744666,23.716716
12,Maranhão,16.669614,16.421773,16.708894,11.665173,11.437359,19.881056,20.739589
13,Piauí,17.960366,16.948094,18.231789,12.258324,11.204814,20.494063,23.69544
14,Ceará,19.499293,18.52712,19.882469,12.186936,12.821323,23.019718,24.952274
15,Rio Grande do Norte,18.307740,18.101853,18.445218,11.166909,11.086286,23.54708,24.422884
16,Paraíba,18.920816,18.88792,18.945306,12.480204,12.400831,23.642936,24.03565
17,Pernambuco,19.306249,18.950219,19.418444,12.312833,12.868821,23.35788,24.243396
18,Alagoas,20.217129,19.165111,20.560451,12.121839,13.35716,24.093655,25.856637
19,Sergipe,18.826541,17.264294,19.317934,10.830511,11.270341,21.740902,25.637681
20,Bahia,17.849776,17.538007,17.935566,10.551673,10.982808,22.57273,23.217119
21,Sudeste,17.104218,16.834863,17.397989,11.933522,12.180843,20.732969,21.990431
22,Minas Gerais,17.502141,17.179387,17.707564,11.31972,11.61912,22.18665,23.075751
23,Espírito Santo,17.111106,16.51061,17.478861,11.798571,12.017589,20.464462,22.196626
24,Rio de Janeiro,16.716263,16.097467,17.24306,12.000036,12.864896,19.203741,20.957728
25,São Paulo,17.071295,16.964437,17.25548,12.123044,12.2352,20.771186,21.76762
26,Sul,15.527769,15.570983,15.406088,11.546629,11.159487,19.012969,19.338734
27,Paraná,15.390122,15.453295,15.307289,11.240085,10.815611,18.896661,19.36538
28,Santa Catarina,16.039355,16.124417,15.616235,12.339052,11.517342,19.414764,19.646573
29,Rio Grande do Sul,15.356709,15.337269,15.448203,11.308447,11.519941,18.86823,19.10772
30,Centro-Oeste,15.000763,14.826985,15.078025,10.546799,10.332059,18.220683,19.33104
31,Mato Grosso do Sul,15.309783,14.902105,15.567204,10.446213,11.12692,18.5932,19.542761
32,Mato Grosso,14.239989,14.083513,14.270209,9.479654,9.265734,17.782825,18.695923
33,Goiás,15.186471,14.962622,15.296966,10.636424,10.531883,18.440842,19.587913
34,Distrito Federal,15.096351,15.061306,15.126295,11.377952,10.481279,17.738123,19.307332
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Fonte: IBGE. Pesquisa Nacional por Amostra de ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Notas:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,(1) Calculado apenas para as pessoas que decla...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,(2) Exclusive as pessoas sem declaração das ho...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
juntado =  comp.merge(tIBGE, on=["Sigla", "Código", "Estado"], how="inner")

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False