In [1]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\12500070\appdata\roaming\python\python312\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in c:\users\12500070\appdata\roaming\python\python312\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\program files\python312\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata in c:\users\12500070\appdata\roaming\python\python312\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in c:\program files\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.3.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [28]:
import pandas as pd
from pathlib import Path
import openpyxl

In [29]:
path = "CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

In [30]:
df = pd.read_excel(path, sheet_name="Municípios", header=2)
colunas_populacao = [
    "População Município 2010\n(Sinopse)",
    "População 2010 (Alterações de Limites até 2022)1",
    "População Censo 2022",
]

df.head()

,Unnamed: 0,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,NaN,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,NaN,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,NaN,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,NaN,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,NaN,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0

In [31]:
populacao_estado = (df.groupby("UF")[["População 2010 (Alterações de Limites até 2022)1","População Censo 2022",]].sum().reset_index())


populacao_estado["Crescimento_2010_2022"] = (populacao_estado["População Censo 2022"]- populacao_estado["População 2010 (Alterações de Limites até 2022)1"])

populacao_estado = populacao_estado.sort_values("Crescimento_2010_2022", ascending=False).reset_index(drop=True)

populacao_estado

,UF,População 2010 (Alterações de Limites até 2022)1,População Censo 2022,Crescimento_2010_2022
0,SP,41262199.0,44411238.0,3149039.0
1,SC,6248436.0,7610361.0,1361925.0
2,GO,6001789.0,7056495.0,1054706.0
3,PR,10444526.0,11444380.0,999854.0
4,MG,19597330.0,20539989.0,942659.0
5,MT,3035122.0,3658649.0,623527.0
6,PA,7581051.0,8120131.0,539080.0
7,AM,3483985.0,3941613.0,457628.0
8,CE,8451644.0,8794957.0,343313.0
9,ES,3514952.0,3833712.0,318760.0
10,MS,2449024.0,2757013.0,307989.0
11,PE,8796055.0,9058931.0,262876.0
12,DF,2572159.0,2817381.0,245222.0
13,PB,3766528.0,3974687.0,208159.0
14,MA,6574789.0,6776699.0,201910.0
15,RS,10693929.0,10882965.0,189036.0
16,RR,450479.0,636707.0,186228.0
17,PI,3119097.0,3271199.0,152102.0
18,SE,2067852.0,2210004.0,142152.0
19,RN,3168027.0,3302729.0,134702.0
20,TO,1383445.0,1511460.0,128015.0
21,BA,14017071.0,14141626.0,124555.0
22,AC,733559.0,830018.0,96459.0
23,RJ,15989929.0,16055174.0,65245.0
24,AP,669526.0,733759.0,64233.0
25,RO,1562409.0,1581196.0,18787.0
26,AL,3120887.0,3127683.0,6796.0
27,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,0.0,0.0,0.0
28,Nota: Para o cálculo das taxas de crescimento ...,0.0,0.0,0.0

In [33]:
caminho_arquivo = Path.cwd() / "populacao_estado.csv"

populacao_estado.to_csv(caminho_arquivo,sep=";",index=False,encoding="utf-8-sig")

In [34]:
populacao_municipio = df[
    [
        "UF",
        "COD. UF",
        "COD. MUNIC",
        "NOME DO MUNICÍPIO",
        "População 2010 (Alterações de Limites até 2022)1",
        "População Censo 2022",
    ]
].copy()

populacao_municipio["Crescimento_2010_2022"] = (populacao_municipio["População Censo 2022"]- populacao_municipio["População 2010 (Alterações de Limites até 2022)1"])

populacao_municipio = populacao_municipio.sort_values("Crescimento_2010_2022", ascending=False).reset_index(drop=True)

populacao_municipio.head(20)

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População 2010 (Alterações de Limites até 2022)1,População Censo 2022,Crescimento_2010_2022
0,AM,13.0,2603.0,Manaus,1802014.0,2063689.0,261675.0
1,DF,53.0,108.0,Brasília,2572159.0,2817381.0,245222.0
2,SP,35.0,50308.0,São Paulo,11253503.0,11451999.0,198496.0
3,SP,35.0,52205.0,Sorocaba,586816.0,723682.0,136866.0
4,GO,52.0,8707.0,Goiânia,1301912.0,1437366.0,135454.0
5,RR,14.0,100.0,Boa Vista,284313.0,413486.0,129173.0
6,SC,42.0,5407.0,Florianópolis,421240.0,537211.0,115971.0
7,PA,15.0,5536.0,Parauapebas,153908.0,267836.0,113928.0
8,MS,50.0,2704.0,Campo Grande,786774.0,898100.0,111326.0
9,PB,25.0,7507.0,João Pessoa,723515.0,833932.0,110417.0
10,MG,31.0,70206.0,Uberlândia,604013.0,713224.0,109211.0
11,ES,32.0,5002.0,Serra,417330.0,520653.0,103323.0
12,SC,42.0,9102.0,Joinville,515288.0,616317.0,101029.0
13,MT,51.0,3403.0,Cuiabá,553202.0,650877.0,97675.0
14,SP,35.0,43402.0,Ribeirão Preto,604682.0,698642.0,93960.0
15,PE,26.0,11101.0,Petrolina,293962.0,386791.0,92829.0
16,SP,35.0,41000.0,Praia Grande,262051.0,349935.0,87884.0
17,SC,42.0,11900.0,Palhoça,137334.0,222598.0,85264.0
18,MT,51.0,7909.0,Sinop,113099.0,196312.0,83213.0
19,MA,21.0,11201.0,São José de Ribamar,161937.0,244579.0,82642.0

In [35]:
caminho_municipip = Path.cwd() / "planilha_municipio.csv"

populacao_municipio.to_csv(caminho_municipip,sep=";",index=False,encoding="utf-8-sig")

In [36]:
display(populacao_municipio.head(10))

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População 2010 (Alterações de Limites até 2022)1,População Censo 2022,Crescimento_2010_2022
0,AM,13.0,2603.0,Manaus,1802014.0,2063689.0,261675.0
1,DF,53.0,108.0,Brasília,2572159.0,2817381.0,245222.0
2,SP,35.0,50308.0,São Paulo,11253503.0,11451999.0,198496.0
3,SP,35.0,52205.0,Sorocaba,586816.0,723682.0,136866.0
4,GO,52.0,8707.0,Goiânia,1301912.0,1437366.0,135454.0
5,RR,14.0,100.0,Boa Vista,284313.0,413486.0,129173.0
6,SC,42.0,5407.0,Florianópolis,421240.0,537211.0,115971.0
7,PA,15.0,5536.0,Parauapebas,153908.0,267836.0,113928.0
8,MS,50.0,2704.0,Campo Grande,786774.0,898100.0,111326.0
9,PB,25.0,7507.0,João Pessoa,723515.0,833932.0,110417.0